[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/apps/scheduler.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "albion-scheduler"
[services.deploy]
startCommand = "node dist/apps/scheduler.js"

[[services]]
name = "albion-kills"
[services.deploy]
startCommand = "node dist/apps/kills-worker.js"

[[services]]
name = "albion-metrics"
[services.deploy]
startCommand = "node dist/apps/metrics-http.js"
[services.deploy.healthcheck]
path = "/healthz"
timeout = 300
